akeneo/pim-community-standard

- UPGRADE-1.4.md
- Fix Download URL
- Need to clear cache before composer update because of Symfony version bump.
> [TR] PIM-4928 : minor changes to 1.3 - 1.4 migration instructions

- UPGRADE-1.4.md
- upgrades/1.3-1.4/mongodb/MediaMigration.php
- upgrades/1.3-1.4/mongodb/migrate_medias.php
- Fix the Mongo medias migration script to clean product values that contained deleted medias (it was keeped in 1.3 but removed in 1.4)
- Update the upgrade.md to provide queries to help people who already migrated to clean their product values
> [TR] PIM-5055: Fix medias migration for removed product media values

- UPGRADE-1.4.md
- upgrades/1.3-1.4/mongodb/MediaMigration.php
- upgrades/1.3-1.4/mongodb/repair_medias_normalized_data.php
Fixes cases where product normalized values are not sync with the file info table:
```
db.pim_catalog_product.aggregate([
{$match: {_id: ObjectId("55d3ef54db4c5dda148d2d82")}}, 
{$unwind: "$values"}, 
{$match: {"values.media": {$exists: true}}}, 
{$project: {"values": 1, "normalizedData.image": 1}}
]).pretty();
```
```
{
"_id" : ObjectId("55d3ef54db4c5dda148d2d82"),
"normalizedData" : {
"image" : {
"id" : NumberLong(1658),
"key" : "e/9/6/1/e96189b7afd9f923ef81fe712e24d717113a9935_55d3ef51eaaed_ruk901r600ww00_image___1439952721_zf_r600_glam.jpg",
"originalFilename" : "zf-r600-glam.jpg"
}
},
"values" : {
"_id" : ObjectId("55d3ef54db4c5dda148d2d99"),
"assetIds" : [ ],
"attribute" : NumberLong(421),
"entity" : DBRef("pim_catalog_product", ObjectId("55d3ef54db4c5dda148d2d82"), …
```
> [TR][SLA] PIM-5342: Added missing script that migrate product normalized valuesof medias for mongodb users

- composer.json
Since we moved remaining oro bundles in pim-community-dev this vcs is useless
> Remove useless vcs

- UPGRADE-1.5.md
A side note: When reading the Upgrade document in the `pim-community-standard` repository, the first section "Catalog Bundle & Component" may be misleading: It talks about the files in `pim-community-dev` like f.ex. the `config.yml` which have a different content than described in the `pim-community-standard` repository.
> Doc: Fix path and download link in UPGRADE-1.5.md

- web/app.php
| Q                                 | A
| --------------------------------- | ---
| Review and 2 GTM                  | No
This PR add missing lines in the web/app.php file that we forgot to add when we upgrade from sf2.3 to sf2.7. If this line is not added it doesn't work with the APC cache.
> Update file according to sf2.7 #4937

- .gitignore
- bin/docker/pim-dependencies.sh
- bin/docker/pim-front.sh
- bin/docker/pim-initialize.sh
- docker-compose.yml.dist
This PR bring to standard edition the last changes on Docker scripts from the `akeneo/pim-enterprise-dev`.
It removes the execution of `npm install` from the script `bin/docker/pim-initialize.sh`, and put it in a new script `bin/docker/pim-dependencies.sh` with `composer update`. This way, a developer can choose to install the PIM dependencies or not, before launching an install.
It also update the `docker-compose.yml.dist` file, using official Elasticsearch image instead of the one maintained by Docker.
> Extract dependencies install into a new Docker script helper

- composer.json
Packagist fails to fetch the 1.6 branch and tags due to a misconfiguration of the composer.json file license name:
```
Reading composer.json of akeneo/pim-community-standard (1.6) Importing branch 1.6 (1.6.x-dev) 
Skipped branch 1.6, Invalid package information: License "OSL 3.0" is not a valid SPDX license 
identifier, see https://spdx.org/licenses/ if you use an open license. If the software is closed-source, 
you may use "proprietary" as license.
```
> Update composer license name to fix packagist fetch issue

- UPGRADE-2.1.md
It could be misleading and we could think that the whole step 4 was optional, but only the first bullet.
This way, we could miss to run `composer update`, so it means don't have the migration files in the `upgrade` folder.
> Clarify upgrade guide from 2.0 to 2.1 to avoid to miss the step of running composer update

- docker/httpd.conf
This change is mandatory with recent version of the "httpd" image. Without it, it is not possible to run containers anymore.
https://github.com/docker-library/httpd/pull/87#commitcomment-27128090
> Add MPM module to Apache Docker configuration

- bin/docker/pim-front.sh
- bin/docker/pim-initialize.sh
- docker-compose.yml.dist
This PR adds small improvements to the Docker Compose file and helper scripts:
- use `rm` command to delete cache, but only in containers (so it prevent deleting anything on the user machine outside of the PIM project)
- fix some minor default in YAML syntax
- remove `PHP_XDEBUG_REMOTE_HOST` as it is not needed most of the time (and is documented anyway)
- put more folder/files in read-only
- change the mapping of the port to avoid using already used ports on the host machine
> Small Docker Compose enhancements

- docker-compose.yml.dist
Declaring a network is useless when there is only one, as Docker Compose already do it by itself.
> Remove network from docker-compose.yml.dist

- composer.json
My PHP 7.1 executable is named `php7.1`, not `php`, which is my 7.0 version.
Use instead `@php` in the composer.json scripts to use the same executable as the one is currently running
> En route to Akeneo 2.0

- docker-compose.yml
This PR update the `docker-compose.yml` file to use the `node:10-slim` image, to fit the Akeneo 3.0 requirements.
> Use "akeneo/node" image in docker-compose

- .circleci/config.yml
- composer.json
- master alias must be only on master branch
- we do not need other aliases on **comparable** versions
> Remove composer aliases

- composer.json
This is already what `akeneo/pim-community-dev` accepts, so no BC-break.
Setting PHP to 7.2 and more can lead to confusion if people try to install it, assuming it can work with PHP 7.3 or 7.4, when it doesn't and is not even installable.
This already leads to a mistake on Bitnami setup: they seems to propose Akeneo 3.2 with PHP 7.3, and of course it doesn't work. A discussion was started about that [on SUG](https://akeneopim-ug.slack.com/archives/C0HLGPDL0/p1572233479124400).
> Accept only PHP 7.2 as Composer required version

- composer.json
We moved these dependencies in require-dev in CE and EE dev, so we must integrate them here
> Add required dev dependencies

- .circleci/config.yml
- composer.json
This PR fixes dev dependencies for Standard Edition.
Also, it adds a CI step to test the installation with the last 4.0 dev branch.
The previous steps only tests installation with the last **stable** tag of pim-community-dev and don't detect errors on the current **dev** version.
Indeed, the standard edition was effectively broken since several days and was not detected by the CI until the yesterday tag, which is by the way also broken.
That's why we must alost test the installation with the last **@dev** version of pim-community-dev.
> Add CI step to run with dev dependencies

- .circleci/config.yml
- README.md
The previous config was testing:
- the last tag of CE branch 4.0.x
- and then the dev branch 4.0
As everything was in the same jobs, there were some bugs.
For example, yarn was not re-installed when modifying composer to load the development CE branch. 
If a new dependency was added in the dev CE branch, it was failing due to this installation bug of the CI. 
Splitting it in two jobs allows us to:
- test the release version exactly the same way as we document how to create a new project in the documentation
- test the CE branch without relying of previously installed stuff, which can be incomplete/not up to date
> Test independently released CE version and development CE branch

- .circleci/test_migrations_from_4_0.sh
When building the front part of the PIM, instead of relying on independant make steps,
it's better to directly call the `make front` : https://github.com/akeneo/pim-community-dev/blob/07faafa9934bdc43c29f0cf49a9e983a772c03ae/std-build/Makefile#L49
The latest changes isolated the `dsm` & `css` from the `javascript-dev`
> Fix the make target used for building the front

- .circleci/config.yml
- .circleci/test_migrations_from_6_0.sh
In this PR, I changed : 
- The PHP version used by pim-community-standard to 8.1 => as now the PIM need PHP 8.1
- I updated the image used by CircleCi => It the same image than the EE CircleCi
Related change: 
- https://github.com/akeneo/pim-enterprise-dev/pull/15343
- https://github.com/akeneo/pim-community-dev/pull/18252
- https://github.com/akeneo/pim-onboarder/pull/1038
> RAB-1127: Use PHP 8.1 in order to launch composer install on standard edition

- .circleci/test_migrations_from_6_0.sh
- README.md
In this PR: 
- I fixed the wrong documentation about the docker image tag
- I removed the memory_limit documentation as we didn't need it anymore 
- I refactored .circleci/test_migrations_from_6_0.sh in order to be more readable
> RAB-1218: Fix documentation and refactor code

- .circleci/test_migrations_from_6_0.sh
In this PR, I fixed the standard nightly => the CI does not pass anymore because during the migration we pass from 7.6.2 to 8.5. This is not allowed by Elasticsearch we should use the 7.17.7 before migration to 8.5.
> Fix elasticsearch need to be migrated to 7.17.7 before upgrading to 8.5
