- app/AppKernel.php
- app/config/pim_parameters.yml
- composer.json
Related to https://github.com/akeneo/pim-community-dev/commit/60c52f7bb823134b93f9c03669eb4027172237ef
> Last changes are not taken back in standard edition

- app/AppKernel.php
- app/config/pim_parameters.yml
| Q                    | A
| -------------------- | ---
| Bug fix?             | Y
| New feature?         | N
| BC breaks?           | N
| CI currently passes? | -
| Tests pass?          | -
| Scenarios pass?      | -
| Checkstyle issues?*  | -
| PMD issues?**        | -
| Changelog updated?   | -
| Fixed tickets        | PIM-3743
| DB schema updated?   | Y
| Migration script?    | Y
| Doc PR               | N
> PIM-3743: Add paramater to take doctrine migrations from pim-community-dev

- UPGRADE-1.3.md
| Q                    | A
| -------------------- | ---
| Bug fix?             | y
| New feature?         |n
| BC breaks?           |n
| CI currently passes? |
| Tests pass?          |
| Scenarios pass?      |
| Checkstyle issues?*  |
| PMD issues?**        |
| Changelog updated?   |
| Fixed tickets        | PIM-3816
| DB schema updated?   |
| Migration script?    |
| Doc PR               |
> Modify UPGRADE-1.3.md to add migrations

- UPGRADE-1.3.md
- app/config/pim_parameters.yml
| Q                    | A
| -------------------- | ---
| Bug fix?             | y
| New feature?         |
| BC breaks?           |
| CI currently passes? |
| Tests pass?          |
| Scenarios pass?      |
| Checkstyle issues?*  |
| PMD issues?**        |
| Changelog updated?   |
| Fixed tickets        | PIM-3816
| DB schema updated?   |
| Migration script?    |
| Doc PR               |
> PIM-3816 : change doctrine migration dir and update UPGRADE-1.3.md

- README.md
> [TR] Format pim:install command

- CHANGELOG-1.4.md
- upgrades/1.3-1.4/common/AbstractMediaMigration.php
- upgrades/1.3-1.4/orm/MediaMigration.php
Fix media migration performance
> [TR] PIM-5017 : fix media migration with lots of files

- README.md
to avoid to duplicate content between online doc and repo
> [DX] Update readme for the standard edition

- .gitignore
The ".idea" should be remove in the locale computer not in a global .gitignore file as it is dedicated to the developer environment
> Clean .gitignore removing .idea from it

- README.md
Revert dropped composer install of the readme
> Add composer install in the readme

- README.md
To match the link from the website
> Fix composer install title

- .gitignore
We should ignore all `app/config/*_local.yml` config files
> Ignore local config files

- app/AppKernel.php
- app/config/routing.yml
Apply modifications done in:
https://github.com/akeneo/pim-community-dev/pull/5374
https://github.com/akeneo/pim-community-dev/pull/5435
https://github.com/akeneo/pim-community-dev/pull/5432
And reorder the bundles.
> Clean kernel after the modifications on dev distribution

- UPGRADE-1.6.md
- UPGRADE-1.7.md
- app/AppKernel.php
- app/SymfonyRequirements.php
- app/check.php
- app/config/config.yml
- app/config/routing.yml
- composer.json
Contains
- all the updates done in pim-community-dev repository (app/config, AppKernel, UPGRADE...)
- the update of Requirement of Sf
- update current branch master
> Merge 1.7 -> master

- README.md
> Remove useless travisci badges (we now use jenkinsci)

- CHANGELOG-1.7.md
- UPGRADE-1.7.md
Some minor typos that broke the markdown parsing rendering
> Fixed some glitches

- .gitignore
- UPGRADE-1.7.md
- UPGRADE-1.8.md
- app/AppKernel.php
- app/SymfonyRequirements.php
- app/config/config.yml
- app/config/pim_parameters.yml
- composer.json
- package.json.dist
This PR makes the necessary changes to get single storage and webpack working
> TIP-731: Adds missing config for single storage and webpack

- .gitignore
- bin/docker/pim-front.sh
- bin/docker/pim-initialize.sh
- docker-compose.yml.dist
- docker/akeneo.conf
Same configuration than community dev (removing behat part)
> Introduce docker configuration

- app/PimRequirements.php
The goal of this PR is to allow to connect to a remote database because the CheckRequirements breaks before.
> Fix database requirements

- app/PimRequirements.php
Little regression noticed by @ahocquard
> Fix-requirements: Database is not mandatory

- app/AppKernel.php
cf https://github.com/akeneo/pim-community-dev/pull/6554
> Enable web server bundle

- UPGRADE-1.7.md
See https://github.com/akeneo/pim-community-dev/pull/6577
> Improve the upgrade file when setting the security about API

- .gitignore
- app/config/config.yml
- app/config/parameters.yml.dist
Use the new indexed and configuration from catalog modeling rework
> Update elasticsearch configuration

- app/config/config.yml
- app/config/parameters.yml.dist
cf https://github.com/akeneo/pim-community-dev/pull/6773
> Fix standard master

- .gitignore
- bin/docker/pim-dependencies.sh
- bin/docker/pim-front.sh
- bin/docker/pim-initialize.sh
- docker-compose.yml.dist
- docker/akeneo.conf
See this PR for more context https://github.com/akeneo/pim-community-dev/pull/6798.
> Add docker-compose file and Docker helper scripts

- bin/docker/pim-initialize.sh
> Fix "pim-initialize" docker script

- app/config/config.yml
See https://github.com/akeneo/pim-community-dev/pull/6931 for description
> TIP-808: Use version strategy for frontend assets

- web/app.php
See same evo for CE dev : https://github.com/akeneo/pim-community-dev/pull/6969
> Tip814 c estd

- bin/docker/pim-front.sh
- bin/docker/pim-initialize.sh
- package.json
Run webpack in dev environment and use it in the Docker helper scripts
See https://github.com/akeneo/pim-community-dev/pull/7018 for description.
> Add a "webpack-dev" command

- app/PimRequirements.php
https://github.com/akeneo/pim-docs/blob/master/install_pim/system_requirements/system_requirements.rst.inc
> PIM-6833 Synchronize requirements with docs

- UPGRADE-1.7.md
The content had been accidentally deleted on the 2.0 release. No need to review its content.
> Undo UPGRADE-1.7.md deletion

- UPGRADE-2.1.md
Please check if I haven't forgotten something in the steps of the upgrade.
> API-554: prepare 2.1 release

- docker-compose.yml.dist
See contribution PR here for more details: https://github.com/akeneo/pim-community-dev/pull/6943
> Run Elasticsearch container in dev mode

- composer.json
Bring to pim-enterprise-dev https://github.com/akeneo/pim-community-dev/pull/7179 contribution.
> Add "index_hosts" to the incenteev parameters

- UPGRADE-2.3.md
Add Migrate the routing manually step in upgrade md
> Release: Fix upgrade.md to take routing into account

- app/AppKernel.php
- app/config/config.yml
- app/config/routing.yml
Deleted in pim-community-dev in PR https://github.com/akeneo/pim-community-dev/pull/8402
> remove PimJsFormValidation and APYJsFormValidation from AppKernel.php

- app/config/pim_parameters.yml
cf https://github.com/akeneo/pim-community-dev/pull/8765 && https://github.com/akeneo/pim-enterprise-dev/pull/4632/files
> PIM-7621 - add new axes on System Information

- app/PimRequirements.php
With this PR, the standard edition will automatically inherits of requirements defined in the CE dev.
Related CE dev PR: https://github.com/akeneo/pim-community-dev/pull/8783
> Uses requirements from CE dev

- .circleci/config.yml
- .gitignore
- bin/docker/pim-setup.sh
To test the correct installation with community dev.
> Circleci nightly build

- composer.json
We should only manage dev-master alias
> Fix dev-master composer alias

- package.json
This PR updates jQuery and dropzone to match the pim-community-dev
> PIM-8026: Update jQuery and dropzone.js

- .circleci/config.yml
- app/AppKernel.php
JMS serialiazer and KNP menu have been removed from the CE dependencies
> Fix dependencies problem

- .circleci/config.yml
- app/AppKernel.php
- app/config/config.yml
- app/config/config_behat.yml
- app/config/config_dev.yml
- app/config/config_prod.yml
- app/config/config_test.yml
- bin/docker/pim-front.sh
- bin/docker/pim-initialize.sh
- package.json
This PR removes assetic from the config files and updates package.json with the new commands to compile .less files https://github.com/akeneo/pim-community-dev/pull/9576
> TIP-820: Replace assetic bundle with lessjs

- package.json
See: https://github.com/akeneo/pim-community-dev/pull/9607
> Compile form extensions with node

- CHANGELOG.md
- UPGRADE.md
- app/config/pim_parameters.yml
- docker-compose.override.yml.dist
- docker-compose.yml
- package.json
Copy of config files from the pim-community-dev
> Prepare release 3.1

- web/app.php
See https://github.com/akeneo/pim-community-dev/pull/10081
> PIM-8352: Add comment about trusted proxy and HTTPS

- package.json
CE-dev: akeneo/pim-community-dev#10217
EE-dev: akeneo/pim-enterprise-dev#6280
EE-std: https://github.com/akeneo/pim-enterprise-standard/pull/889
> Fix production dependencies requirements

- package.json
See https://github.com/akeneo/pim-community-dev/pull/12880
> GITHUB-APD-227: add communication panel

- .circleci/config.yml
- .circleci/test_migrations_from_4_0.sh
Same as https://github.com/akeneo/pim-enterprise-standard/pull/1315 for CE
> CPM-30: nightly job to test migrations from 4.0

- .circleci/config.yml
- .circleci/test_migrations_from_6_0.sh
Test migrations from 6.0 -> master instead of 5.0 -> master.
Also switch from cron CI job to trigger CI job.
> Test migrations from 6.0

- composer.json
see https://github.com/akeneo/pim-community-dev/pull/18879
> Revert fix version of ramsey/uuid on standard side
